name: heroku-jupyter
dependencies:
  - python
  # bind notebook version (compatibility to pgcontents)
  - notebook=6
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython=6
  # bind tornado version (websocket problems)
  - tornado
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography 
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - pgcontents==0.6
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
